= {product} FAQs
:navtitle: FAQs

If you are new to {product}, these frequently asked questions are for you.

== Introduction

=== What is {product}?

The {product} is a an open-source product from {company}.

{product} combines the industry-standard AMQP 0.9.1 (RabbitMQ) API with the cloud-native and horizontally scalable {pulsar-reg} streaming platform, providing a powerful way to modernize your RabbitMQ infrastructure, improve performance, and reduce costs.

{product} is open source and is included in https://www.ibm.com/docs/en/supportforpulsar[IBM Elite Support for {pulsar}].


=== What is required to run {product}?

{product} is a proxy for RabbitMQ that is powered by {pulsar-short}. It requires a compatible {pulsar-short} release to operate. The following {pulsar-short} releases are supported:

* {luna-streaming} 2.8.0+
* {pulsar} 2.9.0+


=== What are the {product} limitations?

See xref:ROOT:index.adoc#limitations[].

=== Is {product} an open-source project?

Yes, {product} is open source using the Apache 2.0 license. You can find the source code on the GitHub repository https://github.com/datastax/starlight-for-rabbitmq[datastax/starlight-for-rabbitmq].

=== Does {product} support Kubernetes?

Yes.
You can run the {product} on {luna-streaming} or {pulsar-short} running on any Kubernetes platform, including Minikube, K8d, Kind, Google Kubernetes Engine (GKE), Microsoft Azure Kubernetes Service, Amazon Kubernetes Service (AKS), and other commonly used platforms.

You can deploy {product} as proxy extension using the https://github.com/datastax/pulsar-helm-chart[{company} Helm chart for {luna-streaming} and {pulsar}].

=== Where is the {product} public GitHub repository?

You can access the {product} repository https://github.com/datastax/starlight-for-rabbitmq[here].

=== How do I install {product}?

Follow the xref:installation:getting-started.adoc[getting started] instructions.
