= {product}

{product} acts as a proxy between your https://www.rabbitmq.com/[RabbitMQ] application and https://pulsar.apache.org/[{pulsar-reg}].
It implements the AMQP 0.9.1 protocol used by RabbitMQ clients and translates AMQP frames and concepts to {pulsar-short} ones.
{product} can be run as a standalone Java application, a {pulsar-short} https://github.com/apache/pulsar/wiki/PIP-41%3A-Pluggable-Protocol-Handler[Pluggable Protocol Handler], or a https://github.com/apache/pulsar/wiki/PIP-99%3A-Pulsar-Proxy-Extensions[{pulsar-short} Proxy extension].

== How {product} works

AMQP 0.9.1, the protocol RabbitMQ uses, employs the concepts of `Exchanges`, `Queues`, and `Bindings` to provide basic routing capabilities inside the message broker.
These concepts are mapped to {pulsar-short} topics and features.

{product} acts as a proxy and uses the {pulsar-short} binary protocol to communicate with the brokers.
This method allows RabbitMQ applications to leverage {pulsar-short} features like load balancing of the topics on the brokers, batching of messages, partitioning of topics, and load balancing of the data on the consumers.

For more information, see xref:operations:protocol-handler.adoc[].

[#deployment-options]
== Deployment options

include::ROOT:partial$deployment-options.adoc[]

For instructions, see xref:installation:getting-started.adoc[].

[#limitations]
== Limitations

{product} doesn't support the following features:

* Topic and headers exchanges
* Exclusive consumers
* Non durable exchanges and queues
* Transient messages (all messages are persisted)
* Authorization support

Because RabbitMQ and {pulsar-short} work differently, {product} was designed to realize the most benefit from {pulsar-short}'s scalability.
This means that canceling an AMQP consumer re-queues the messages that were received through it because it also closes the associated {pulsar-short} consumers.