= {product}

{product} acts as a proxy between your https://www.rabbitmq.com/[RabbitMQ] application and https://pulsar.apache.org/[{pulsar-reg}] cluster. It implements the AMQP 0.9.1 protocol used by RabbitMQ clients and translates AMQP frames and concepts to {pulsar-short} ones. {product} can be run as a standalone Java application, a {pulsar-short} Protocol Handler, or a {pulsar-short} Proxy Extension.

== How {product} works

AMQP 0.9.1, the protocol RabbitMQ uses, employs the concepts of `Exchanges`, `Queues`, and `Bindings` to provide basic routing capabilities inside the message broker.
These concepts are mapped to {pulsar-short} topics and features.

{product} acts as a proxy and uses the {pulsar-short} binary protocol to communicate with the brokers. This method allows RabbitMQ applications to leverage {pulsar-short} features like load balancing of the topics on the brokers, batching of messages, partitioning of topics, and load balancing of the data on the consumers.

== Deployment options

{product} can be run in various deployments:

* Standalone Java application
Running {product} as a standalone Java application has the advantage of not impacting the resources used by the {pulsar-short} cluster but on the other hand you need to deploy and manage the lifecycle of an additional runtime.

* https://github.com/apache/pulsar/wiki/PIP-41%3A-Pluggable-Protocol-Handler[{pulsar-short} Pluggable Protocol Handler]
Deploying {product} in the broker as a Protocol Handler avoids having to deploy another runtime but there will be resources used by {product} to handle the traffic that can have an impact on the load balancing algorithms used by {pulsar-short}.

* https://github.com/apache/pulsar/wiki/PIP-99%3A-Pulsar-Proxy-Extensions[{pulsar-short} Proxy extension]
Deploying {product} in the {pulsar-short} Proxy as a Proxy Extension avoids having to deploy another runtime if you already use the {pulsar-short} Proxy and it will not have a big impact on the {pulsar-short} Proxy functioning. Note that Proxy Extensions will be available in {pulsar-short} v2.9+.

== Limitations

The following capabilities have not been implemented:

* Header exchanges (topic exchanges have been added)
* Exclusive consumers
* Non durable exchanges and queues
* Transient messages (all messages are persisted)

Because RabbitMQ and {pulsar-short} work differently, {product} was designed to make the most of {pulsar-short}'s scalability.
This means that canceling an AMQP consumer will re-queue the messages that were received through it because it also closes the associated {pulsar-short} consumers.