= Get started
:navtitle: Installation

== Downloading {product}

. Download the {product} `tar` file from the https://github.com/datastax/starlight-for-rabbitmq/releases[{product} GitHub repository].

+
The following files are available in the `tar` file:

+
[cols="1,1"]
|===
| File | Purpose

| starlight-rabbitmq-1.1.0-jar-with-dependencies.jar | Running as a standalone Java application
| starlight-rabbitmq-1.1.0.nar | Running as a protocol handler or a proxy extension

|===

. Extract the files from the `tar` with the following command:

+
[source,bash,subs="+quotes"]
----
tar xvfz starlight-rabbitmq-**VERSION**-all.tar.gz
----

== Deploy {product}

include::ROOT:partial$deployment-options.adoc[]

The deployment options you can use depend on your {pulsar-short} deployment.

[tabs]
======
{astra-streaming}::
+
--
When you enable {product} in {astra-streaming}, it is deployed as a Protocol Handler in the {pulsar-short} brokers.
Because {astra-streaming} manages the {pulsar-short} cluster for you, you cannot use the other {product} deployment options.


--

{luna-streaming}::
+
--
[tabs]
====
Protocol Handler::
+
include::ROOT:partial$run-as-protocol-handler-simple.adoc[]

Proxy Extension::
+
include::ROOT:partial$run-as-proxy-extension.adoc[]

Standalone Java application::
+
include::ROOT:partial$run-as-standalone.adoc[]
====
--

Self-managed::
+
--
[tabs]
====
Protocol Handler::
+
include::ROOT:partial$run-as-protocol-handler-simple.adoc[]

Proxy Extension::
+
include::ROOT:partial$run-as-proxy-extension.adoc[]

Standalone Java application::
+
include::ROOT:partial$run-as-standalone.adoc[]
====
--
======

== Test {product}

You can use a `RabbitMQ/AMQP-0.9.1` client or a tool such as https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/[RabbitMQ PerfTest]
to test {product} after deploying it.

For example, the following Python script creates a queue, publishes a message that is routed to the queue, reads the message from the queue, and then deletes the queue:

[source,python]
----
#!/usr/bin/env python
import pika

connection = pika.BlockingConnection(pika.ConnectionParameters(port=5672))
channel = connection.channel()

try:
    channel.queue_declare("test-queue")
    print("created test-queue queue")
    channel.basic_publish(exchange="", routing_key="test-queue", body="test".encode('utf-8'))
    print("published message test")
    _, _, res = channel.basic_get(queue="test-queue", auto_ack=True)
    assert res is not None, "should have received a message"
    print("received message: " + res.decode())
    channel.queue_delete("test-queue")
    print("deleted test-queue queue")
finally:
    connection.close()
----

== Next steps