= Get started with the {product} extension
:navtitle: Installation
:description: Use the {product} extension with {pulsar-reg}.

The {product-repo}[{product} extension] enables https://www.rabbitmq.com/[RabbitMQ] protocol support for https://pulsar.apache.org/[{pulsar-reg}].

The extension acts as a proxy between your RabbitMQ application and {pulsar-short} cluster.
It implements the AMQP 0.9.1 protocol used by RabbitMQ clients and translates AMQP frames and concepts to {pulsar-short} concepts.

== Deployment options for {product}

include::ROOT:partial$deployment-options.adoc[]

The deployment options you can use depend on your {pulsar-short} deployment.

== Deploy on {astra-stream}

When you enable {product} in {astra-stream}, it is deployed as a protocol handler in the {pulsar-short} cluster.
Because {astra-stream} manages the {pulsar-short} cluster for you, you cannot use the other {product} deployment options.

The following steps explain how to enable the {product} protocol handler in an {astra-stream} {pulsar-short} cluster, and then get the connection details for your RabbitMQ client:

. In the {astra-ui-link} header, click icon:grip[name="Applications"], and then select *Streaming*.

. xref:astra-streaming:getting-started:index.adoc[Create a tenant] or click the name of an existing tenant.

. Go to your tenant's **Connect** tab, select **RabbitMQ**, and then click **Enable RabbitMQ**.

. Review the information about the {product} extension, and then click **Enable RabbitMQ** to confirm that you want to enable this extension on your tenant.
+
[IMPORTANT]
====
This action creates a configuration file and a `rabbitmq` namespace in your {astra-stream} tenant automatically.

The `rabbitmq` namespace is required for the {product} extension to function properly.
It is a permanent namespace that cannot be removed except by deleting the entire tenant and all of its data.
====

. Save the RabbitMQ connection details to a file named `rabbitmq.conf`.
The actual values depend on your {astra-stream} tenant's configuration and cloud provider.
+
.rabbitmq.conf
[source,plaintext,subs="+quotes,+attributes"]
----
username: **TENANT_NAME**
password: masked
host: rabbitmq-**PROVIDER**-**REGION**.streaming.datastax.com
port: 5671
virtual_host: **TENANT_NAME**/rabbitmq
amqp_URI: masked@rabbitmq-**PROVIDER**-**REGION**.streaming.datastax.com:5671/**TENANT_NAME**/rabbitmq
----
+
The `password` and first part of the `amqp_URI` are masked with asterisks (`*`).
+
[TIP]
====
In {astra-stream}, if you click icon:download[name="Download"] or icon:clipboard[name="Copy"], then a {pulsar-short} token is included in the `password` field automatically.
You can also generate a token on your tenant's **Settings** tab.
====

. To test your {product} deployment and connect a RabbitMQ client, see xref:installation:quickstart.adoc[].

== Deploy a protocol handler on {luna-streaming} or a self-managed {pulsar-short} cluster

include::ROOT:partial$luna-streaming-rename-tip.adoc[]

You can embed {product} directly into the {pulsar-short} brokers by loading it as a protocol handler using a `nar` file:

. Download the {product} `tar` file from the {product-repo}/releases[{product} GitHub repository].

. Extract the files from the `tar`:
+
[source,bash,subs="+quotes"]
----
tar xvfz starlight-rabbitmq-**VERSION**-all.tar.gz
----

. Copy the `starlight-rabbitmq-**VERSION**.nar` file, which is used to run {product} as a protocol handler, to the appropriate directory in your {pulsar-short} broker installation directory, such as the `/protocols` directory.

. Create or edit a {pulsar-short} broker configuration file, such as `broker.conf` or `standalone.conf`.

. Set the {product} protocol handler configuration.
For example, if the `nar` file is in the `./protocols` directory:
+
.broker.conf
[source,plaintext]
----
messagingProtocols=rabbitmq
protocolHandlerDirectory=./protocols
----

. Set the AMQP service listeners.
For example:
+
.broker.conf
[source,plaintext]
----
amqpListeners=amqp://127.0.0.1:5672
advertisedAddress=127.0.0.1
----
+
The hostname value in `amqpListeners` is the same as {pulsar-short} broker's `advertisedAddress`.

. Start the {pulsar-short} broker.

. To test your {product} deployment and connect a RabbitMQ client, see xref:installation:quickstart.adoc[].

== Deploy a proxy extension on {luna-streaming} or a self-managed {pulsar-short} cluster

include::ROOT:partial$luna-streaming-rename-tip.adoc[]

You can embed {product} into the {pulsar-short} Proxy by loading it as a proxy extension:

. Download the {product} `tar` file from the {product-repo}/releases[{product} GitHub repository].

. Extract the files from the `tar`:
+
[source,bash,subs="+quotes"]
----
tar xvfz starlight-rabbitmq-**VERSION**-all.tar.gz
----

. Copy the `starlight-rabbitmq-**VERSION**.nar` file, which is used to run {product} as a proxy extension, to the appropriate directory in your {pulsar-short} Proxy installation directory, such as the `/proxyextensions` directory.

. Create or edit a {pulsar-short} Proxy configuration file, such as `proxy.conf`.

. Set the {product} proxy extension configuration.
For example, if the `nar` file is in the `./proxyextensions` directory
+
.proxy.conf
[source,plaintext]
----
proxyExtensions=rabbitmq
proxyExtensionsDirectory=./proxyextensions
----

. Set the AMQP service listeners.
For example:
+
.proxy.conf
[source,plaintext]
----
amqpListeners=amqp://127.0.0.1:5672
advertisedAddress=127.0.0.1
----
+
The hostname value in listeners is the same as {pulsar-short} proxy's `advertisedAddress`.

. Start the {pulsar-short} proxy.

. To test your {product} deployment and connect a RabbitMQ client, see xref:installation:quickstart.adoc[].

== Deploy a standalone Java application on {luna-streaming} or a self-managed {pulsar-short} cluster

include::ROOT:partial$luna-streaming-rename-tip.adoc[]

You can run {product} as a standalone Java application.
The `jar` file for running {product} as a standalone Java application is available in the {product} `tar` file.

. Download the {product} `tar` file from the {product-repo}/releases[{product} GitHub repository].

. Extract the files from the `tar`:
+
[source,bash,subs="+quotes"]
----
tar xvfz starlight-rabbitmq-**VERSION**-all.tar.gz
----
+
The path to the `jar` file is `/starlight-rabbitmq/target/starlight-rabbitmq-**VERSION**-jar-with-dependencies.jar`.

. In a configuration file, set the URLs of the {pulsar-short} brokers and the {zookeeper-reg} configuration store.
For example:
+
[source,plaintext]
----
brokerServiceURL=pulsar://localhost:6650
brokerWebServiceURL=http://localhost:8080
configurationStoreServers=localhost:2181
----

. Run the `jar` file as a Java application with the configuration file path in the `--config` (`-c`) option:
+
[source,bash]
----
java -jar ./starlight-rabbitmq/target/starlight-rabbitmq-${version}-jar-with-dependencies.jar -c conf/starlight-for-rabbitmq.conf
----

. To test your {product} deployment and connect a RabbitMQ client, see xref:installation:quickstart.adoc[].

== Deploy a protocol handler on {luna-streaming} with a Helm chart (deprecated)

include::ROOT:partial$luna-streaming-rename-tip.adoc[]

The {product} extension is included in the `luna-streaming-all` image used to deploy an {luna-streaming} cluster.
The {company} {pulsar-short} Helm chart simplifies deployment of {product} as a protocol handler.

The following steps explain how to deploy a {company} {pulsar-short} Helm chart to create a simple {pulsar-short} cluster with the {product} extension ready for use.

[IMPORTANT]
=====
The {company} {pulsar-short} Helm chart used in this example is deprecated.
For Kubernetes deployments, {company} recommends xref:kaap-operator:ROOT:index.adoc[{kaap}].
=====

. Make sure you meet the following prerequisites:
+
* Install https://helm.sh/docs/intro/install/[Helm 3 CLI] version 3.8.0 or later.
* Install https://kubernetes.io/docs/tasks/tools/[kubectl CLI] version 1.23.4 or later.
* Have access to a Kubernetes cluster with permission to create a namespace, deployments, and pods.

. Add the {company} {pulsar-short} Helm chart repo to your Helm store:
+
[source,shell]
----
helm repo add datastax-pulsar https://datastax.github.io/pulsar-helm-chart
----

. Install the Helm chart using a xref:installation:attachment$values.yaml[minimal values file].
The following command creates a Helm release named `my-pulsar-cluster` using the {company} {pulsar-short} Helm chart within a Kubernetes namespace named `datastax-pulsar`.
This minimal configuration creates only the essential components and has no ingress or load balanced services.
+
[source,shell]
----
helm install \
  --namespace datastax-pulsar \
  --create-namespace \
  --values path/to/values.yaml \
  --version 3.0.4 \
  my-pulsar-cluster \
  datastax-pulsar/pulsar
----

. Wait for the broker pod to reach a running state.
It might restart a few times while the components start up.
+
[source,shell]
----
kubectl -n datastax-pulsar wait --for=condition=Ready pod/pulsar-broker-0 --timeout=120s
----

. Enable port forwarding for the {pulsar-short} Admin and {product} services that are running on the Kubernetes cluster.
+
You don't need to open the {pulsar-short} binary port to accept new messages when using {product}.
This is because RabbitMQ clients communicate using the AMQP protocol over the RabbitMQ port (5672).
+
.. In a new terminal, port forward the {pulsar-short} Admin service:
+
[source,shell]
----
kubectl port-forward -n datastax-pulsar service/pulsar-broker 8080:8080
----
+
.. In a separate terminal window, port forward the {product} service:
+
[source,shell]
----
kubectl port-forward -n datastax-pulsar service/pulsar-proxy 5672:5672
----

The {company} {pulsar-short} Helm chart deployed {product} on the {pulsar-short} proxy and opened the correct port.
The forwarded ports allow you to access {pulsar-short} and {product} services when running RabbitMQ client scripts and using CLI tools locally.
Your applications can now communicate with {pulsar-short} as if it were a real RabbitMQ host, as explained in xref:installation:quickstart.adoc[].