You can embed {product} into the {pulsar-short} Proxy by loading it as a proxy extension.
+
. Download the {product} `tar` file from the https://github.com/datastax/starlight-for-rabbitmq/releases[{product} GitHub repository].
+
. Extract the files from the `tar`:
+
[source,bash,subs="+quotes"]
----
tar xvfz starlight-rabbitmq-**VERSION**-all.tar.gz
----
+
Copy the `starlight-rabbitmq-**VERSION**.nar` file, which is used to run {product} as a proxy extension, to the appropriate directory in your {pulsar-short} Proxy installation directory, such as the `/proxyextensions` directory.
+
. Create or edit a {pulsar-short} Proxy configuration file, such as `proxy.conf`.
+
. Set the {product} proxy extension configuration.
For example, if the `nar` file is in the `./proxyextensions` directory
+
.proxy.conf
[source,conf]
----
proxyExtensions=rabbitmq
proxyExtensionsDirectory=./proxyextensions
----
+
. Set the AMQP service listeners.
For example:
+
.proxy.conf
[source,conf]
----
amqpListeners=amqp://127.0.0.1:5672
advertisedAddress=127.0.0.1
----
+
The hostname value in listeners is the same as {pulsar-short} proxy's `advertisedAddress`.
+
. Start the {pulsar-short} proxy.