You can embed {product} directly into the {pulsar-short} brokers by loading it as a protocol handler.
+
. Download the {product} `tar` file from the {product-repo}/releases[{product} GitHub repository].
+
. Extract the files from the `tar`:
+
[source,bash,subs="+quotes"]
----
tar xvfz starlight-rabbitmq-**VERSION**-all.tar.gz
----
+
Copy the `starlight-rabbitmq-**VERSION**.nar` file, which is used to run {product} as a protocol handler, to the appropriate directory in your {pulsar-short} broker installation directory, such as the `/protocols` directory.
+
. Create or edit a {pulsar-short} broker configuration file, such as `broker.conf` or `standalone.conf`.
+
. Set the {product} protocol handler configuration.
For example, if the `nar` file is in the `./protocols` directory:
+
.broker.conf
[source,conf]
----
messagingProtocols=rabbitmq
protocolHandlerDirectory=./protocols
----
+
. Set the AMQP service listeners.
For example:
+
.broker.conf
[source,conf]
----
amqpListeners=amqp://127.0.0.1:5672
advertisedAddress=127.0.0.1
----
+
The hostname value in `amqpListeners` is the same as {pulsar-short} broker's `advertisedAddress`.
+
. Start the {pulsar-short} broker.